---
# kitchen-vagrant
#driver:
#  name: vagrant
#  require_chef_omnibus: latest
#  network:
#    - ["private_network", {ip: "33.33.33.10"}]

# kitchen-docker
driver:
  name: docker
  socket: tcp://127.0.0.1:2375
  use_sudo: false
  remove_images: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[statsd::default]
      - recipe[chef_handler::default]
      - recipe[chef_handler::json_file]
    attributes: {
    }
